In [1]:
import pandas as pd
from pathlib import Path

In [2]:
data_dir = Path(r'C:\Users\******\для объединения')  # путь к папке, где лежат файлы excel, которые нужно объединить

df = (pd.concat([pd.read_excel(f, skiprows=7).assign(file_name=f.stem)  # сборка всех файлов в один датафрэйм в цикле
                 for f in data_dir.glob("*.xlsx")], ignore_index=True))

In [3]:
df.head()  # первые 5 строк объединенной таблицы

,Код торгпреда,Торгпред,Дата визита,Код клиента,Клиент,Адрес клиента,Время начала визита,Время конца визита,Продолжительность визита,Кол-во заказов,Кол-во накладных,Причины отказа от заказа/накладной,Статус маршрута,"№ посещения, факт","№ посещения, план",Расстояние от активности до точки,"Км, факт",file_name
0,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-7961,Кнап Д.В.(Теремок),"Фрунзе ул, дом № 76",2023-12-04 10:06:02,2023-12-04 10:10:05,1900-01-01 00:04:03,0,0,отказ,Плановый,1.0,27.0,7.0,15.904,Лист в ДЗ для АД 1
1,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002565,"САВА ООО Артем ул.Фрунзе 74 ""Дворик""","Фрунзе ул, дом № 74",2023-12-04 10:10:11,2023-12-04 10:14:54,1900-01-01 00:04:43,1,0,Зак: 1,Плановый,2.0,21.0,47.0,15.940,Лист в ДЗ для АД 1
2,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002676,Сазикова И.Л. г.Артем ул.Макаренко 32,"ул Макаренко, д. 32",2023-12-04 10:21:43,2023-12-04 10:23:54,1900-01-01 00:02:11,1,0,Зак: 1,Внеплановый,3.0,NaN,741.0,17.048,Лист в ДЗ для АД 1
3,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002026,Пак С.А. ул.Вокзал.110,"Вокзальная ул, дом № 110",2023-12-04 10:24:07,2023-12-04 10:29:27,1900-01-01 00:05:20,0,0,отказ,Плановый,4.0,2.0,18.0,17.048,Лист в ДЗ для АД 1
4,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-3937,Ким С.В.№4,"Пионерская ул, дом № 1",2023-12-04 10:29:32,2023-12-04 10:45:14,1900-01-01 00:15:42,1,0,Зак: 1,Плановый,5.0,25.0,140.0,17.239,Лист в ДЗ для АД 1

In [4]:
df.loc[df.duplicated()]  # проверка итогового датафрэйма на наличие дубликатов строк. Дубликатов нет

Empty DataFrame
Columns: [Код торгпреда, Торгпред, Дата визита, Код клиента, Клиент, Адрес клиента, Время начала визита, Время конца визита, Продолжительность визита, Кол-во заказов, Кол-во накладных, Причины отказа от заказа/накладной, Статус маршрута, № посещения, факт, № посещения, план, Расстояние от активности до точки, Км, факт, file_name]
Index: []

На следующем шаге хочу к этой таблице добавить информацию о торгпредах из файла "Лист в ДЗ для АД 3". Загружаю данные из файла в отдельный датафрэйм.

In [5]:
df_torgpred = pd.read_excel(r'C:\Users\******\Лист в ДЗ для АД 3.xlsx')

In [6]:
df_torgpred.head()

,Группа агентов,Агент,Действует,Подразделение,Бизнес-регион,Код
0,Вода,NaN,NaN,NaN,NaN,NaN
1,Вода розница Артем,NaN,NaN,NaN,NaN,NaN
2,Вода розница Артем,Вафина Светлана Анатольевна,Да,Вода розница Артем,Артем,1037.0
3,Вода розница Артем,Исрафилов Владимир,Да,Вода розница Артем,Б.Камень,1038.0
4,Вода розница Артем,Поденкова Евгения,Да,Вода розница Артем,Артем,1039.0

In [7]:
df_torgpred = df_torgpred.dropna()  # удаление строк с пустыми значениями

In [8]:
df_torgpred.head()

,Группа агентов,Агент,Действует,Подразделение,Бизнес-регион,Код
2,Вода розница Артем,Вафина Светлана Анатольевна,Да,Вода розница Артем,Артем,1037.0
3,Вода розница Артем,Исрафилов Владимир,Да,Вода розница Артем,Б.Камень,1038.0
4,Вода розница Артем,Поденкова Евгения,Да,Вода розница Артем,Артем,1039.0
5,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0
8,Мондэлис розница,Косницкая Анастасия Владимировна,Да,Мондэлиз Розница,Владивосток,2.0

Заметила, что какие-то имена агентов содержат фамилию, имя и отчество, а какие-то - только фамилию и имя. Предполагаю, что это одни и те же люди. Поэтому, чтобы объединить две таблицы по полю с именем агента, в столбцах "Торгпред" и "Агент" нужно оставить только имя и фамилию, новый столбец с именем и фамилией назвать "Торгпред ФИ".

In [9]:
def split_name(full_name):  # функция, которая оставляет имя и фамилию
    x = full_name.split(' ')[0:2]
    return ' '.join(x)

In [10]:
df['Торгпред ФИ'] = df.Торгпред.apply(split_name)  # применяем функцию на объединенном датафрэйме

In [11]:
df.head()

,Код торгпреда,Торгпред,Дата визита,Код клиента,Клиент,Адрес клиента,Время начала визита,Время конца визита,Продолжительность визита,Кол-во заказов,Кол-во накладных,Причины отказа от заказа/накладной,Статус маршрута,"№ посещения, факт","№ посещения, план",Расстояние от активности до точки,"Км, факт",file_name,Торгпред ФИ
0,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-7961,Кнап Д.В.(Теремок),"Фрунзе ул, дом № 76",2023-12-04 10:06:02,2023-12-04 10:10:05,1900-01-01 00:04:03,0,0,отказ,Плановый,1.0,27.0,7.0,15.904,Лист в ДЗ для АД 1,Федоренко Мария
1,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002565,"САВА ООО Артем ул.Фрунзе 74 ""Дворик""","Фрунзе ул, дом № 74",2023-12-04 10:10:11,2023-12-04 10:14:54,1900-01-01 00:04:43,1,0,Зак: 1,Плановый,2.0,21.0,47.0,15.940,Лист в ДЗ для АД 1,Федоренко Мария
2,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002676,Сазикова И.Л. г.Артем ул.Макаренко 32,"ул Макаренко, д. 32",2023-12-04 10:21:43,2023-12-04 10:23:54,1900-01-01 00:02:11,1,0,Зак: 1,Внеплановый,3.0,NaN,741.0,17.048,Лист в ДЗ для АД 1,Федоренко Мария
3,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002026,Пак С.А. ул.Вокзал.110,"Вокзальная ул, дом № 110",2023-12-04 10:24:07,2023-12-04 10:29:27,1900-01-01 00:05:20,0,0,отказ,Плановый,4.0,2.0,18.0,17.048,Лист в ДЗ для АД 1,Федоренко Мария
4,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-3937,Ким С.В.№4,"Пионерская ул, дом № 1",2023-12-04 10:29:32,2023-12-04 10:45:14,1900-01-01 00:15:42,1,0,Зак: 1,Плановый,5.0,25.0,140.0,17.239,Лист в ДЗ для АД 1,Федоренко Мария

In [12]:
df_torgpred['Торгпред ФИ'] = df_torgpred.Агент.apply(split_name) # применяем функцию на втором датафрэйме

In [13]:
df_torgpred.head()

,Группа агентов,Агент,Действует,Подразделение,Бизнес-регион,Код,Торгпред ФИ
2,Вода розница Артем,Вафина Светлана Анатольевна,Да,Вода розница Артем,Артем,1037.0,Вафина Светлана
3,Вода розница Артем,Исрафилов Владимир,Да,Вода розница Артем,Б.Камень,1038.0,Исрафилов Владимир
4,Вода розница Артем,Поденкова Евгения,Да,Вода розница Артем,Артем,1039.0,Поденкова Евгения
5,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0,Федотова Яна
8,Мондэлис розница,Косницкая Анастасия Владимировна,Да,Мондэлиз Розница,Владивосток,2.0,Косницкая Анастасия

Объединяем два датафрэйма по столбцу "Торгпред ФИ"

In [14]:
df_merged = df.merge(df_torgpred, how = 'left', on = 'Торгпред ФИ')

In [15]:
df_merged

,Код торгпреда,Торгпред,Дата визита,Код клиента,Клиент,Адрес клиента,Время начала визита,Время конца визита,Продолжительность визита,Кол-во заказов,...,Расстояние от активности до точки,"Км, факт",file_name,Торгпред ФИ,Группа агентов,Агент,Действует,Подразделение,Бизнес-регион,Код
0,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-7961,Кнап Д.В.(Теремок),"Фрунзе ул, дом № 76",2023-12-04 10:06:02,2023-12-04 10:10:05,1900-01-01 00:04:03,0,...,7.0,15.904,Лист в ДЗ для АД 1,Федоренко Мария,NaN,NaN,NaN,NaN,NaN,NaN
1,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002565,"САВА ООО Артем ул.Фрунзе 74 ""Дворик""","Фрунзе ул, дом № 74",2023-12-04 10:10:11,2023-12-04 10:14:54,1900-01-01 00:04:43,1,...,47.0,15.940,Лист в ДЗ для АД 1,Федоренко Мария,NaN,NaN,NaN,NaN,NaN,NaN
2,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002676,Сазикова И.Л. г.Артем ул.Макаренко 32,"ул Макаренко, д. 32",2023-12-04 10:21:43,2023-12-04 10:23:54,1900-01-01 00:02:11,1,...,741.0,17.048,Лист в ДЗ для АД 1,Федоренко Мария,NaN,NaN,NaN,NaN,NaN,NaN
3,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-00-00002026,Пак С.А. ул.Вокзал.110,"Вокзальная ул, дом № 110",2023-12-04 10:24:07,2023-12-04 10:29:27,1900-01-01 00:05:20,0,...,18.0,17.048,Лист в ДЗ для АД 1,Федоренко Мария,NaN,NaN,NaN,NaN,NaN,NaN
4,A-A-000000137,Федоренко Мария (Перспектива),2023-12-04,A-3937,Ким С.В.№4,"Пионерская ул, дом № 1",2023-12-04 10:29:32,2023-12-04 10:45:14,1900-01-01 00:15:42,1,...,140.0,17.239,Лист в ДЗ для АД 1,Федоренко Мария,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
429,A-A-000000135,Федотова Яна (Вода),2023-12-04,A-8034,"Цикун В.В. п.Новый, ул.Ленина 2а","Надеждинский р-н, Новый п, Ленина ул, дом № 2а",2023-12-04 12:20:45,2023-12-04 12:24:29,1900-01-01 00:03:44,1,...,82.0,12.363,Лист в ДЗ для АД 2,Федотова Яна,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0
430,A-A-000000135,Федотова Яна (Вода),2023-12-04,A-5868,Шаповалова(Каприз),"Надеждинский р-н, Новый п, Молодежная ул, дом № 6",2023-12-04 12:27:13,2023-12-04 12:34:31,1900-01-01 00:07:18,1,...,12.0,12.591,Лист в ДЗ для АД 2,Федотова Яна,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0
431,A-A-000000135,Федотова Яна (Вода),2023-12-04,A-5419,Яковенко 2,"Надеждинский р-н, Новый п, Первомайская ул, до...",2023-12-04 12:38:14,2023-12-04 12:46:46,1900-01-01 00:08:32,1,...,94.0,13.049,Лист в ДЗ для АД 2,Федотова Яна,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0
432,A-A-000000135,Федотова Яна (Вода),2023-12-04,A-00-00001028,"Горохова О.Л. п.Новый, ул.Первомайская 1а","Надеждинский р-н, Новый п, Первомайская ул, до...",2023-12-04 12:51:31,2023-12-04 12:56:07,1900-01-01 00:04:36,1,...,1.0,13.365,Лист в ДЗ для АД 2,Федотова Яна,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0
433,A-A-000000135,Федотова Яна (Вода),2023-12-04,A-00-00001166,"Алеут п.Новый, Первомайская 6","Надеждинский р-н, Новый п, Первомайская ул, зд...",2023-12-04 13:00:33,2023-12-04 13:00:38,1900-01-01 00:00:05,0,...,41.0,13.935,Лист в ДЗ для АД 2,Федотова Яна,Вода розница Артем,Федотова Яна,Да,Вода розница Артем,Артем,1040.0

Итоговый датафрэйм сохраняем в виде файла excel

In [16]:
df_merged.to_excel(r'C:\Users\******\final_data.xlsx')